apiVersion: apps/v1
kind: Deployment
metadata:
  name: pools-app-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pools-app-backend-pod
  template:
    metadata:
      labels:
        app: pools-app-backend-pod
    spec:
      containers:
        - name: pools-app-backend-container
          image: kakarot404/new-project-backend:v2  
          ports:
            - containerPort: 1234 
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:                            # Reference to the secret containing credentials
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:                            # Reference to the secret containing credentials
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:                            # Reference to the secret containing credentials
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---

apiVersion: v1
kind: Service
metadata:
  name: pools-app-backend-service
spec:
  selector:
    app: pools-app-backend-pod
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  type: LoadBalancer

