apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: "mongodb://mr_pool:As21kseG7maP@pools-app-mongodb-service:27017/PoolsApp?authSource=admin&retryWrites=true&w=majority"