apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.podName }}
    spec:
      containers:
        - name: {{ .Values.backend.container.name }}
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.container.port }}
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:                            # Reference to the secret containing credentials
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:                            # Reference to the secret containing credentials
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:                            # Reference to the secret containing credentials
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.podName }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetport }}
  type: LoadBalancer

